### ISSUE TITLE
How to hook for in game api?

### ISSUE THREAD

**Issue by Kavan72** [moonshadow565/ssl_key_dump#3]
@moonshadow565 first thank you this is awesome. do you know how to intercept in game apis ? fiddler or any other tools not working cuz they are checking certificate.

**Comment by moonshadow565** [comment]
1. You set path to keylog.txt in wireshark preferences.
2. You start wireshark capture
3. Done

You can add keylog.txt after you captured your trafic or before, the way wireshark makes it work is bit a fucky as usual because it only decrypts trafic with currently set key file in global preferences.
At least you don't need to reset or backup your keylog on each capture as wireshark will automatically figure what log entry is appropriate for each capture.
I also think you could export your decrypted data from wireshark into fiddler for better viewing but no idea how that works exactly.

**Comment by Kavan72** [comment]
@moonshadow565 thank for quick reply. It's working fine for `RiotClientServices.exe` i'm talking about ingame apis for valorant. `RiotClientServices.exe` only contains some apis which required for chat and rms services. you can check all in game apis [here](https://github.com/liamcottle/valorant.js/blob/master/endpoints.txt)

**Comment by moonshadow565** [comment]
yeah you will need to inject it into Valorant.exe  for that

one thing to note is that you should hardcode offsets for it to hook faster and capture initial ssl handshake and data
so its something like this:

1. inject
2. log offsets
3. edit the code to use hardoced offsets
4. inject again
5. all the same stuff with wireshark

as to how to inject you should figure that yourself or try finding someone else that knows how to do it
i'm not willing to disclose how to do it publicly

**Comment by Kavan72** [comment]
are you sure because i don't think so `Valorant.exe` is using this `RiotGamesApi.dll` and `RiotClientFoundation.dll`. and on this repo there is one branch call `config` this is for generate the ssl config? is this right ? and do you have discord account to avoid the public communication? my discord id is `Hidan#4772`

**Comment by moonshadow565** [comment]
It doesn't need to use those .dlls.
It hooks anything using openssl, those .dlls are just hardcoded list of modules to look into for openssl (since riot compiles openssl statically into all their .exes and .dlls)

https://github.com/moonshadow565/ssl_key_dump/blob/master/main.cpp#L28
``nullptr`` here means "this executable.exe" when passed to GetModuleHandleA

You can find me on fantome discord(need to have common server to DM on discord): https://discord.gg/SUHpgaF
